apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-existing-pvc
  namespace: neo4j
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3-for-neo4j
  volumeName: neo4j-existing-pv
  resources:
    requests:
      storage: 20Gi
