apiVersion: v1
data:
  admin-user: bGlhbUAhMDk=
  admin-password: bGlhbQ==
kind: Secret
metadata:
  creationTimestamp: "2026-03-28T09:45:44Z"
  name: kube-prometheus-stack-grafana
  namespace: monitoring
  resourceVersion: "67517"
  uid: 4c572004-85b2-46e8-8793-b193a355d5fd
type: Opaque
